<%@page import="java.util.Properties"%>  
<%@page import="java.io.FileInputStream"%>  
<%@page import="java.io.FileNotFoundException"%>
<%@page import="java.io.IOException"%>
<% 
//国际化
	String local = (String)session.getAttribute("session_language"); 
	Properties properties = new Properties();
	try {
		FileInputStream fis = new FileInputStream(this.getClass().getClassLoader().getResource("/").getPath()+"slight_"+local+".properties");
		try {
			properties.load(fis);
			fis.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	} catch (FileNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		System.out.println("can not find file");
	} 
	
	String integration_power = properties.getProperty("integration_power");
	String bigest_electricity = properties.getProperty("bigest_electricity");
	String light_operating_err = properties.getProperty("light_operating_err");
	String wait_start_use = properties.getProperty("wait_start_use");
	String please_choose_phone_number = properties.getProperty("please_choose_phone_number");
	String please_enter_name = properties.getProperty("please_enter_name");
	String userinfo = properties.getProperty("userinfo");
	String make_sure = properties.getProperty("make_sure");
	String no_relevant_data = properties.getProperty("no_relevant_data");
	String add2 = properties.getProperty("add2");
	String old_password = properties.getProperty("old_password");
	String add1 = properties.getProperty("add1");
	String shut_down = properties.getProperty("shut_down");
	String please_enter_repair_person = properties.getProperty("please_enter_repair_person");
	String device_number = properties.getProperty("device_number");
	String department_name = properties.getProperty("department_name");
	String abnormal_lamp = properties.getProperty("abnormal_lamp");
	String single_light_controller = properties.getProperty("single_light_controller");
	String effective = properties.getProperty("effective");
	String open_light = properties.getProperty("open_light");
	String gateway_anomaly = properties.getProperty("gateway_anomaly");
	String no_permission = properties.getProperty("no_permission");
	String temperature = properties.getProperty("temperature");
	String make_sure_choose_data = properties.getProperty("make_sure_choose_data");
	String road_light_status = properties.getProperty("road_light_status");
	String please_enter_gateway_number = properties.getProperty("please_enter_gateway_number");
	String time_is_null = properties.getProperty("time_is_null");
	String standard = properties.getProperty("standard");
	String import_from_excel = properties.getProperty("import_from_excel");
	String summary = properties.getProperty("summary");
	String please_enter_group_name_2 = properties.getProperty("please_enter_group_name_2");
	String light_standard = properties.getProperty("light_standard");
	String strategy_adjust = properties.getProperty("strategy_adjust");
	String device_type = properties.getProperty("device_type");
	String please_enter_department_name = properties.getProperty("please_enter_department_name");
	String operate = properties.getProperty("operate");
	String please_choose_file = properties.getProperty("please_choose_file");
	String make_sure_delete2_data = properties.getProperty("make_sure_delete2_data");
	String status_list = properties.getProperty("status_list");
	String please_choose_picture = properties.getProperty("please_choose_picture");
	String test = properties.getProperty("test");
	String stop_mobile = properties.getProperty("stop_mobile");
	String latitude = properties.getProperty("latitude");
	String charactor = properties.getProperty("charactor");
	String account_infomation = properties.getProperty("account_infomation");
	String position = properties.getProperty("position");
	String gateway_name = properties.getProperty("gateway_name");
	String vendor = properties.getProperty("vendor");
	String please_enter_0_180_number = properties.getProperty("please_enter_0_180_number");
	String up_electricity_time = properties.getProperty("up_electricity_time");
	String enter_email_here = properties.getProperty("enter_email_here");
	String device_group_number = properties.getProperty("device_group_number");
	String no_data_in_box = properties.getProperty("no_data_in_box");
	String LOGO = properties.getProperty("LOGO");
	String lamp_short = properties.getProperty("lamp_short");
	String group_explain = properties.getProperty("group_explain");
	String repire_debug = properties.getProperty("repire_debug");
	String visitor = properties.getProperty("visitor");
	String password = properties.getProperty("password");
	String brightness_adjust = properties.getProperty("brightness_adjust");
	String english = properties.getProperty("english");
	String company_location = properties.getProperty("company_location");
	String no_data_any_term = properties.getProperty("no_data_any_term");
	String undervoltage = properties.getProperty("undervoltage");
	String enter_the_department_name_here = properties.getProperty("enter_the_department_name_here");
	String make_sure_delete_picture = properties.getProperty("make_sure_delete_picture");
	String phone = properties.getProperty("phone");
	String enter_phone_number_here = properties.getProperty("enter_phone_number_here");
	String status = properties.getProperty("status");
	String language1 = properties.getProperty("language1");
	String fault_list = properties.getProperty("fault_list");
	String yes = properties.getProperty("yes");
	String add_group_member2 = properties.getProperty("add_group_member2");
	String add_group_member1 = properties.getProperty("add_group_member1");
	String unregister_mobile = properties.getProperty("unregister_mobile");
	String contact_address = properties.getProperty("contact_address");
	String odd_and_even_day = properties.getProperty("odd_and_even_day");
	String brightness_is_null = properties.getProperty("brightness_is_null");
	String add_app_group = properties.getProperty("add_app_group");
	String account_manage = properties.getProperty("account_manage");
	String type = properties.getProperty("type");
	String welcome = properties.getProperty("welcome");
	String please_enter_group_explain = properties.getProperty("please_enter_group_explain");
	String device = properties.getProperty("device");
	String up_and_down_time_not_equal = properties.getProperty("up_and_down_time_not_equal");
	String none_this_department_is_top = properties.getProperty("none_this_department_is_top");
	String return1 = properties.getProperty("return1");
	String please_enter_company_name = properties.getProperty("please_enter_company_name");
	String please_enter_summry = properties.getProperty("please_enter_summry");
	String set_up_and_down_electricity_time = properties.getProperty("set_up_and_down_electricity_time");
	String success_delete = properties.getProperty("success_delete");
	String add_device = properties.getProperty("add_device");
	String modify = properties.getProperty("modify");
	String you_have_not_choose_anything = properties.getProperty("you_have_not_choose_anything");
	String clear_draw = properties.getProperty("clear_draw");
	String brightness_adjustment = properties.getProperty("brightness_adjustment");
	String coordinate_conversion_failed = properties.getProperty("coordinate_conversion_failed");
	String road_light_total_power = properties.getProperty("road_light_total_power");
	String enter_function_values_here = properties.getProperty("enter_function_values_here");
	String multiple_delete_app_group = properties.getProperty("multiple_delete_app_group");
	String gateway_number = properties.getProperty("gateway_number");
	String please_choose_brightness = properties.getProperty("please_choose_brightness");
	String log_name = properties.getProperty("log_name");
	String make_sure_reset_password = properties.getProperty("make_sure_reset_password");
	String this_strategy_not_assign_app_group = properties.getProperty("this_strategy_not_assign_app_group");
	String road_light_open_faliue = properties.getProperty("road_light_open_faliue");
	String make_sure_delete1_data = properties.getProperty("make_sure_delete1_data");
	String total = properties.getProperty("total");
	String statistical_type = properties.getProperty("statistical_type");
	String pole = properties.getProperty("pole");
	String strategy_name = properties.getProperty("strategy_name");
	String please_type_device_name = properties.getProperty("please_type_device_name");
	String please_choose_if_display_LOGO = properties.getProperty("please_choose_if_display_LOGO");
	String brightness_level = properties.getProperty("brightness_level");
	String circle_select = properties.getProperty("circle_select");
	String time_repeat = properties.getProperty("time_repeat");
	String search_type = properties.getProperty("search_type");
	String modify_strategy = properties.getProperty("modify_strategy");
	String road_light_brightness_update_success = properties.getProperty("road_light_brightness_update_success");
	String please_enter_group_name = properties.getProperty("please_enter_group_name");
	String the_packet_has_no_terminal = properties.getProperty("the_packet_has_no_terminal");
	String user = properties.getProperty("user");
	String function_Brief = properties.getProperty("function_Brief");
	String device_number2 = properties.getProperty("device_number2");
	String please_enter_strategy_name = properties.getProperty("please_enter_strategy_name");
	String multiple_add_app_group = properties.getProperty("multiple_add_app_group");
	String bigest_voltage = properties.getProperty("bigest_voltage");
	String over_temperature = properties.getProperty("over_temperature");
	String please_choose_excel = properties.getProperty("please_choose_excel");
	String menber_number = properties.getProperty("menber_number");
	String device_name = properties.getProperty("device_name");
	String not_divide_group = properties.getProperty("not_divide_group");
	String system = properties.getProperty("system");
	String gateway = properties.getProperty("gateway");
	String this_group_can_not_divide_odd_and_even = properties.getProperty("this_group_can_not_divide_odd_and_even");
	String please_choose_end_time = properties.getProperty("please_choose_end_time");
	String road_light_shut_down_success = properties.getProperty("road_light_shut_down_success");
	String make_sure_delete_data = properties.getProperty("make_sure_delete_data");
	String please_choose = properties.getProperty("please_choose");
	String blockout = properties.getProperty("blockout");
	String exception_status = properties.getProperty("exception_status");
	String please_choose_status = properties.getProperty("please_choose_status");
	String group_name = properties.getProperty("group_name");
	String time = properties.getProperty("time");
	String change = properties.getProperty("change");
	String device_combination = properties.getProperty("device_combination");
	String strate_control = properties.getProperty("strate_control");
	String make_sure_divider_open_light = properties.getProperty("make_sure_divider_open_light");
	String road_light_open_success = properties.getProperty("road_light_open_success");
	String over_voltage = properties.getProperty("over_voltage");
	String add_device_tips = properties.getProperty("add_device_tips");
	String please_choose_the_superior_department = properties.getProperty("please_choose_the_superior_department");
	String time_and_brightness_2 = properties.getProperty("time_and_brightness_2");
	String rest_money = properties.getProperty("rest_money");
	String edit = properties.getProperty("edit");
	String smart_divide_group_by_power = properties.getProperty("smart_divide_group_by_power");
	String department_description = properties.getProperty("department_description");
	String repair_self = properties.getProperty("repair_self");
	String smart_divide_group_by_odd_and_even = properties.getProperty("smart_divide_group_by_odd_and_even");
	String function = properties.getProperty("function");
	String email_type_not_correct = properties.getProperty("email_type_not_correct");
	String device_counter = properties.getProperty("device_counter");
	String no = properties.getProperty("no");
	String delete_app_device = properties.getProperty("delete_app_device");
	String person_name = properties.getProperty("person_name");
	String control_strategy = properties.getProperty("control_strategy");
	String download_model = properties.getProperty("download_model");
	String avg_power_factor = properties.getProperty("avg_power_factor");
	String gateway_or_circuit_breaker_exception = properties.getProperty("gateway_or_circuit_breaker_exception");
	String name = properties.getProperty("name");
	String make_sure_divider_group_by_power = properties.getProperty("make_sure_divider_group_by_power");
	String exception_description = properties.getProperty("exception_description");
	String download_wrong_please_refresh = properties.getProperty("download_wrong_please_refresh");
	String email = properties.getProperty("email");
	String please_enter_vendor = properties.getProperty("please_enter_vendor");
	String self_prepare = properties.getProperty("self_prepare");
	String please_choose_a_statistical_type = properties.getProperty("please_choose_a_statistical_type");
	String energy_consumption = properties.getProperty("energy_consumption");
	String comment = properties.getProperty("comment");
	String pole2 = properties.getProperty("pole2");
	String make_sure_divider_group_by_odd_and_even = properties.getProperty("make_sure_divider_group_by_odd_and_even");
	String please_enter_register = properties.getProperty("please_enter_register");
	String repair_result = properties.getProperty("repair_result");
	String coordinate = properties.getProperty("coordinate");
	String gateway_status = properties.getProperty("gateway_status");
	String explain_item = properties.getProperty("explain_item");
	String please_choose_language = properties.getProperty("please_choose_language");
	String month = properties.getProperty("month");
	String manager = properties.getProperty("manager");
	String importt = properties.getProperty("importt");
	String time_and_brightness_at_most_12 = properties.getProperty("time_and_brightness_at_most_12");
	String enter_new_password = properties.getProperty("enter_new_password");
	String location = properties.getProperty("location");
	String make_sure_delete_app_group = properties.getProperty("make_sure_delete_app_group");
	String content = properties.getProperty("content");
	String repair_time = properties.getProperty("repair_time");
	String strategy = properties.getProperty("strategy");
	String function_key = properties.getProperty("function_key");
	String pole_number2 = properties.getProperty("pole_number2");
	String please_choose_xls_file = properties.getProperty("please_choose_xls_file");
	String repair_instructions = properties.getProperty("repair_instructions");
	String phone_number = properties.getProperty("phone_number");
	String normal = properties.getProperty("normal");
	String work_status = properties.getProperty("work_status");
	String group_number = properties.getProperty("group_number");
	String Gatewayrouter_not_this_operations = properties.getProperty("Gatewayrouter_not_this_operations");
	String add_app_device = properties.getProperty("add_app_device");
	String time_for_24hour = properties.getProperty("time_for_24hour");
	String enter_position_here = properties.getProperty("enter_position_here");
	String superior_department = properties.getProperty("superior_department");
	String power_standard = properties.getProperty("power_standard");
	String fault_type = properties.getProperty("fault_type");
	String total_days = properties.getProperty("total_days");
	String please_choose_fault_type = properties.getProperty("please_choose_fault_type");
	String pole_number = properties.getProperty("pole_number");
	String app_explain = properties.getProperty("app_explain");
	String please_enter_contact = properties.getProperty("please_enter_contact");
	String company_contact = properties.getProperty("company_contact");
	String modify_account = properties.getProperty("modify_account");
	String search_device_not_exist_or_wrong = properties.getProperty("search_device_not_exist_or_wrong");
	String keck_delete_group_member = properties.getProperty("keck_delete_group_member");
	String this_login_name_has_exist = properties.getProperty("this_login_name_has_exist");
	String enter_company_location_here = properties.getProperty("enter_company_location_here");
	String date = properties.getProperty("date");
	String total_time = properties.getProperty("total_time");
	String time_and_brightness = properties.getProperty("time_and_brightness");
	String kick_delete = properties.getProperty("kick_delete");
	String phone_number_type_not_correct = properties.getProperty("phone_number_type_not_correct");
	String power_rate_factor = properties.getProperty("power_rate_factor");
	String modify_information = properties.getProperty("modify_information");
	String jump_to_strategy_control_page = properties.getProperty("jump_to_strategy_control_page");
	String please_enter_time_for_24hour = properties.getProperty("please_enter_time_for_24hour");
	String company_name = properties.getProperty("company_name");
	String search_seccess_please_look_light_list2_on_left = properties.getProperty("search_seccess_please_look_light_list2_on_left");
	String type_wrong_name_check_special = properties.getProperty("type_wrong_name_check_special");
	String power = properties.getProperty("power");
	String wait_repair = properties.getProperty("wait_repair");
	String choose_strategy = properties.getProperty("choose_strategy");
	String function_value = properties.getProperty("function_value");
	String export_to_excel = properties.getProperty("export_to_excel");
	String app_group_has_assigned = properties.getProperty("app_group_has_assigned");
	String enter_function_Brief_here = properties.getProperty("enter_function_Brief_here");
	String registe = properties.getProperty("registe");
	String make_sure_shut_down_light = properties.getProperty("make_sure_shut_down_light");
	String day = properties.getProperty("day");
	String enter_this_log_name_here = properties.getProperty("enter_this_log_name_here");
	String please_choose_odd_even_day = properties.getProperty("please_choose_odd_even_day");
	String light_operating_successfully = properties.getProperty("light_operating_successfully");
	String please_enter_repire_explain = properties.getProperty("please_enter_repire_explain");
	String this_number_has_exist = properties.getProperty("this_number_has_exist");
	String exception = properties.getProperty("exception");
	String detail = properties.getProperty("detail");
	String road_light_list_2 = properties.getProperty("road_light_list_2");
	String road_light_list_1 = properties.getProperty("road_light_list_1");
	String search2 = properties.getProperty("search2");
	String search1 = properties.getProperty("search1");
	String serial_number = properties.getProperty("serial_number");
	String circuit_breaker = properties.getProperty("circuit_breaker");
	String please_choose_department = properties.getProperty("please_choose_department");
	String please_enter_iccid = properties.getProperty("please_enter_iccid");
	String voltage = properties.getProperty("voltage");
	String lamp_open_circuit = properties.getProperty("lamp_open_circuit");
	String add_strategy = properties.getProperty("add_strategy");
	String you_have_no_permission = properties.getProperty("you_have_no_permission");
	String please_choose_charactor = properties.getProperty("please_choose_charactor");
	String login_name_contain_letter_number_4_16 = properties.getProperty("login_name_contain_letter_number_4_16");
	String road_light_brightness_update_faliue = properties.getProperty("road_light_brightness_update_faliue");
	String invalid = properties.getProperty("invalid");
	String search_get_device = properties.getProperty("search_get_device");
	String endtime_biger_than_starttime = properties.getProperty("endtime_biger_than_starttime");
	String chinese = properties.getProperty("chinese");
	String if_display_LOGO = properties.getProperty("if_display_LOGO");
	String please_enter_location = properties.getProperty("please_enter_location");
	String please_enter_serial_number = properties.getProperty("please_enter_serial_number");
	String jiebu = properties.getProperty("jiebu");
	String road_light = properties.getProperty("road_light");
	String enter_person_name_here = properties.getProperty("enter_person_name_here");
	String enter_the_department_here = properties.getProperty("enter_the_department_here");
	String belong_gateway = properties.getProperty("belong_gateway");
	String maintenance_man = properties.getProperty("maintenance_man");
	String please_enter_phone = properties.getProperty("please_enter_phone");
	String please_enter_gateway_name = properties.getProperty("please_enter_gateway_name");
	String light_ratio = properties.getProperty("light_ratio");
	String enter_contact_address_here = properties.getProperty("enter_contact_address_here");
	String light_rate = properties.getProperty("light_rate");
	String address = properties.getProperty("address");
	String road_light_exception = properties.getProperty("road_light_exception");
	String feedback_time = properties.getProperty("feedback_time");
	String enter_old_password = properties.getProperty("enter_old_password");
	String odd = properties.getProperty("odd");
	String group_member = properties.getProperty("group_member");
	String end_time = properties.getProperty("end_time");
	String please_enter_company_location = properties.getProperty("please_enter_company_location");
	String enter_company_name_here = properties.getProperty("enter_company_name_here");
	String command_type = properties.getProperty("command_type");
	String normal_cutoff_device = properties.getProperty("normal_cutoff_device");
	String blockout_time = properties.getProperty("blockout_time");
	String cancel = properties.getProperty("cancel");
	String arrears = properties.getProperty("arrears");
	String functional_classification = properties.getProperty("functional_classification");
	String please_enter_one_time_and_brightness_relation = properties.getProperty("please_enter_one_time_and_brightness_relation");
	String temporary_no_data = properties.getProperty("temporary_no_data");
	String new_password = properties.getProperty("new_password");
	String electricity_set = properties.getProperty("electricity_set");
	String keck_delete_app_group = properties.getProperty("keck_delete_app_group");
	String delete_device = properties.getProperty("delete_device");
	String sensor_standard = properties.getProperty("sensor_standard");
	String total_power = properties.getProperty("total_power");
	String ex_24_hours = properties.getProperty("ex_24_hours");
	String add_account = properties.getProperty("add_account");
	String strategy_manage = properties.getProperty("strategy_manage");
	String please_enter_0_90_number = properties.getProperty("please_enter_0_90_number");
	String divide_group_setting = properties.getProperty("divide_group_setting");
	String add_app_select = properties.getProperty("add_app_select");
	String gateway_location = properties.getProperty("gateway_location");
	String enter_company_contact_here = properties.getProperty("enter_company_contact_here");
	String please_enter_app_explain = properties.getProperty("please_enter_app_explain");
	String please_enter_pole_number = properties.getProperty("please_enter_pole_number");
	String short_circuit = properties.getProperty("short_circuit");
	String road_light_number = properties.getProperty("road_light_number");
	String start_time = properties.getProperty("start_time");
	String clear_search_ = properties.getProperty("clear_search_");
	String road_light_has_shut_status = properties.getProperty("road_light_has_shut_status");
	String please_choose_start_time = properties.getProperty("please_choose_start_time");
	String please_upload_xls_file = properties.getProperty("please_upload_xls_file");
	String delete_all = properties.getProperty("delete_all");
	String voltage_exception = properties.getProperty("voltage_exception");
	String enter_function_classification_here = properties.getProperty("enter_function_classification_here");
	String menber_list = properties.getProperty("menber_list");
	String schedule_adjust_brightness = properties.getProperty("schedule_adjust_brightness");
	String brightness_value = properties.getProperty("brightness_value");
	String repair_register = properties.getProperty("repair_register");
	String brightness_percent = properties.getProperty("brightness_percent");
	String super_manager = properties.getProperty("super_manager");
	String road_light_has_open_status = properties.getProperty("road_light_has_open_status");
	String destroy = properties.getProperty("destroy");
	String electricity_time = properties.getProperty("electricity_time");
	String light = properties.getProperty("light");
	String please_choose_device_type = properties.getProperty("please_choose_device_type");
	String none = properties.getProperty("none");
	String circuit_breaker_abnormality = properties.getProperty("circuit_breaker_abnormality");
	String please_choose_repair_result = properties.getProperty("please_choose_repair_result");
	String choose = properties.getProperty("choose");
	String gatewany_number = properties.getProperty("gatewany_number");
	String up_and_down_electricity = properties.getProperty("up_and_down_electricity");
	String app_list = properties.getProperty("app_list");
	String save = properties.getProperty("save");
	String add_divide_group = properties.getProperty("add_divide_group");
	String old_password_wrong = properties.getProperty("old_password_wrong");
	String committing = properties.getProperty("committing");
	String reset = properties.getProperty("reset");
	String click_this_choose_all = properties.getProperty("click_this_choose_all");
	String shut_down_light = properties.getProperty("shut_down_light");
	String please_choose_company = properties.getProperty("please_choose_company");
	String make_sure_adjust_strategy = properties.getProperty("make_sure_adjust_strategy");
	String this_group_can_not_divide_by_power = properties.getProperty("this_group_can_not_divide_by_power");
	String make_sure_up_and_down_electricity_for_select_device = properties.getProperty("make_sure_up_and_down_electricity_for_select_device");
	String deadline = properties.getProperty("deadline");
	String enter_function_key_here = properties.getProperty("enter_function_key_here");
	String number = properties.getProperty("number");
	String longitude = properties.getProperty("longitude");
	String strategy_number = properties.getProperty("strategy_number");
	String export_electricity = properties.getProperty("export_electricity");
	String group_strategy = properties.getProperty("group_strategy");
	String multiple_add = properties.getProperty("multiple_add");
	String delete = properties.getProperty("delete");
	String power_rate = properties.getProperty("power_rate");
	String please_upload_picture_format_file = properties.getProperty("please_upload_picture_format_file");
	String company = properties.getProperty("company");
	String make_sure_add_app_group = properties.getProperty("make_sure_add_app_group");
	String print_voltage = properties.getProperty("print_voltage");
	String please_enter_standard_name = properties.getProperty("please_enter_standard_name");
	String device_group_list = properties.getProperty("device_group_list");
	String remind_infomation = properties.getProperty("remind_infomation");
	String has_repair = properties.getProperty("has_repair");
	String make_sure_adjust_brightness = properties.getProperty("make_sure_adjust_brightness");
	String wrong_search = properties.getProperty("wrong_search");
	String registrant = properties.getProperty("registrant");
	String reset_password = properties.getProperty("reset_password");
	String energy_status = properties.getProperty("energy_status");
	String new_password_contain_letter_number = properties.getProperty("new_password_contain_letter_number");
	String road_light_shut_down_faliue = properties.getProperty("road_light_shut_down_faliue");
	String you_have_not_choose_any_app_group = properties.getProperty("you_have_not_choose_any_app_group");
	String open_road = properties.getProperty("open_road");
	String even = properties.getProperty("even");
	String please_type_device_number = properties.getProperty("please_type_device_number");
	String operate_time = properties.getProperty("operate_time");
	String ordinary_circuit_breaker = properties.getProperty("ordinary_circuit_breaker");
	String Log_out = properties.getProperty("Log_out");//退出登录
	String Modify_information = properties.getProperty("Modify_information");//修改信息
	String background_home_page = properties.getProperty("background_home_page");//后台首页
// 	String system_management = properties.getProperty("system_management");//系统管理
// 	String privilege_management = properties.getProperty("privilege_management");//权限管理
// 	String Menu_management = properties.getProperty("Menu_management");//菜单管理
// 	String Button_management = properties.getProperty("Button_management");//按钮管理
// 	String data_dictionary = properties.getProperty("data_dictionary");//数据字典
// 	String Basic_configuration = properties.getProperty("Basic_configuration");//基础配置
// 	String Common_power_supply = properties.getProperty("Common_power_supply");//普通电源
// 	String configure_energization = properties.getProperty("configure_energization");//通电配置
// 	String Power_on_setting = properties.getProperty("Power_on_setting");//通电设置
// 	String Terminal_assembly = properties.getProperty("Terminal_assembly");//终端组合
// 	String Gateway_and_circuit_breaker = properties.getProperty("gateway_and_circuit_breaker");//网关/断路器
// 	String Integrated_power_supply = properties.getProperty("Integrated_power_supply");//一体化电源
// 	String Single_light_controller = properties.getProperty("Single_light_controller");//单灯控制器
// 	String telegraph_pole = properties.getProperty("telegraph_pole");//电线杆
	String all = properties.getProperty("all");//全部设备
	String signal_strength = properties.getProperty("signal_strength");
	String Initialization = properties.getProperty("Initialization");//初始化
	String viewConfig = properties.getProperty("viewConfig");//查看配置
	
	//
	String effective_status = properties.getProperty("effective_status");
	String period = properties.getProperty("period");
	String apply_days = properties.getProperty("apply_days");
	String adjust_value = properties.getProperty("adjust_value");
	String start_date = properties.getProperty("start_date");
	String end_date = properties.getProperty("end_date");
	String description = properties.getProperty("description");
	String please_choose_type = properties.getProperty("please_choose_type");
	String please_choose_start_date = properties.getProperty("please_choose_start_date");
	String please_choose_end_date = properties.getProperty("please_choose_end_date");
	String please_enter_period = properties.getProperty("please_enter_period");
	String please_enter_days = properties.getProperty("please_enter_days");
	String please_choose_time = properties.getProperty("please_choose_time");
	String please_choose_lightcolor = properties.getProperty("please_choose_lightcolor");
	String please_choose_bright = properties.getProperty("please_choose_bright");
	String please_enter_1_100 = properties.getProperty("please_enter_1_100");
	
	String month_cycle = properties.getProperty("month_cycle");
	String day_apply_days = properties.getProperty("day_apply_days");
	String brightness = properties.getProperty("brightness");
	String coloured_light = properties.getProperty("coloured_light");
	String warn_cold = properties.getProperty("warn_cold");
	String onoff = properties.getProperty("onoff");
	String on = properties.getProperty("on");
	String off = properties.getProperty("off");
	String please_choose_onoff = properties.getProperty("please_choose_onoff");
	
	String add_strategy_set = properties.getProperty("add_strategy_set");
	String kick_delete_strategy = properties.getProperty("kick_delete_strategy");
	String strategyset_name = properties.getProperty("strategyset_name");
	String strategyset_explain = properties.getProperty("strategyset_explain");
	String please_enter_strategyset_name = properties.getProperty("please_enter_strategyset_name");
	String please_enter_strategyset_explain = properties.getProperty("please_enter_strategyset_explain");
	String select_strategy = properties.getProperty("select_strategy");
	String modify_strategy_set = properties.getProperty("modify_strategy_set");
	String term_num_in_strategy = properties.getProperty("term_num_in_strategy");
	String make_sure_add_strategy = properties.getProperty("make_sure_add_strategy");
	String make_sure_del_strategy = properties.getProperty("make_sure_del_strategy");
	
	String add_group = properties.getProperty("add_group");
	String keck_delete_group = properties.getProperty("keck_delete_group");
	String send_strategy = properties.getProperty("send_strategy");
	String cancel_strategy = properties.getProperty("cancel_strategy");
	String send_status = properties.getProperty("send_status");

	String please_choose_month = properties.getProperty("please_choose_month");
	String please_choose_day = properties.getProperty("please_choose_day");
	String please_choose_futureday = properties.getProperty("please_choose_futureday");
	String totm_less_fromtm = properties.getProperty("totm_less_fromtm");
	String make_sure_send_strategy = properties.getProperty("make_sure_send_strategy");
	String make_sure_cancel_strategy = properties.getProperty("make_sure_cancel_strategy");
	String strategy_is_sent = properties.getProperty("strategy_is_sent");
	String strategy_is_not_sent = properties.getProperty("strategy_is_not_sent");
	
	String decive_name = properties.getProperty("device_name");
	String lamp = properties.getProperty("lamp");
	String sensor = properties.getProperty("sensor");
	String breaker = properties.getProperty("breaker");
	
	String delete_strategy = properties.getProperty("delete_strategy");
	String days_morethan_cycle = properties.getProperty("days_morethan_cycle");
	
	String view_assigned_app_group = properties.getProperty("view_assigned_app_group");
	String please_enter_client_name = properties.getProperty("please_enter_client_name");
	String please_enter_client_code = properties.getProperty("please_enter_client_code");
	String make_sure_add_client = properties.getProperty("make_sure_add_client");
	String please_choose_client_by_gateway = properties.getProperty("please_choose_client_by_gateway");
	String device_comment = properties.getProperty("device_comment");
	String device_temperature = properties.getProperty("device_temperature");
	String device_gatewayname = properties.getProperty("device_gatewayname");
	String print_current = properties.getProperty("print_current");
	String print_voltagec = properties.getProperty("print_voltagec");
	String fault_Device_name =properties.getProperty("fault_Device_name");
	String fault_Device_time =properties.getProperty("fault_Device_time");
	String fault_Device_type =properties.getProperty("fault_Device_type");
	String fault_Device_code =properties.getProperty("fault_Device_code");
	String fault_Device_comment =properties.getProperty("fault_Device_comment");
	String pole_nums =properties.getProperty("pole_nums");
	
	String equip_day_week0 =properties.getProperty("equip_day_week0");
	String equip_day_week1=	properties.getProperty("equip_day_week1");
	String equip_day_week2=	properties.getProperty("equip_day_week2");
	String equip_day_week3=properties.getProperty("equip_day_week3");
	String equip_day_week4=properties.getProperty("equip_day_week4");
	String equip_day_week5=properties.getProperty("equip_day_week5");
	String	equip_day_week6=properties.getProperty("equip_day_week6");
	String	equip_gateway_onlinenum=properties.getProperty("equip_gateway_onlinenum");
	String	equip_gateway_num=properties.getProperty("equip_gateway_num");
	String	equip_gateway_onlinerate=properties.getProperty("equip_gateway_onlinerate");
	
	String	equip_light_num=properties.getProperty("equip_light_num");
	String	equip_light_onlinnum=properties.getProperty("equip_light_onlinnum");
	String	equip_light_onlinrate=properties.getProperty("equip_light_onlinrate");
	String	equip_faultnum=properties.getProperty("equip_faultnum");
	String	equip_num=properties.getProperty("equip_num");
	String	equip_fault_rate=properties.getProperty("equip_fault_rate");
	String	equip_unit1=properties.getProperty("equip_unit1");
	String	equip_unit2=properties.getProperty("equip_unit2");
	String	equip_collect=properties.getProperty("equip_collect");
	String	equip_currentdate=properties.getProperty("equip_currentdate");
	
	String	equip_year=properties.getProperty("equip_year");
	String	equip_month=properties.getProperty("equip_month");
	String  equip_date = properties.getProperty("equip_date");
	String  equip_7days=properties.getProperty("equip_7days");
	String	equip_7week=properties.getProperty("equip_7week");
	String	equip_7month=properties.getProperty("equip_7month");
	String  sequenceselect =properties.getProperty("sequenceselect");
	String  equip_light_onlinenum = properties.getProperty("equip_light_onlinenum");//在线设备编码? 
	String  gateway_rest = properties.getProperty("gateway_rest");
	
	String claimGateway = properties.getProperty("claimGateway");
	String make_sure_view = properties.getProperty("make_sure_view");
	String make_sure_Initial = properties.getProperty("make_sure_Initial");
	String code = properties.getProperty("code");
	String claim = properties.getProperty("claim");
	String please_type_code = properties.getProperty("please_type_code");
	String please_type_password = properties.getProperty("please_type_password");
	String make_sure_delete = properties.getProperty("make_sure_delete");
	String can_not_delete = properties.getProperty("can_not_delete");
	
	String equipment_name = properties.getProperty("equipment_name");//设备名称
	String equipment_code = properties.getProperty("equipment_code");//设备编号
	String equipment_comment = properties.getProperty("equipment_comment");//设备描述
	String equipment_type = properties.getProperty("equipment_type");//设备类型
	String del_divide_group = properties.getProperty("del_divide_group");//删除分组
	
	String sms_platform_name = properties.getProperty("sms_platform_name");//sms平台名称
	String sms_platform_data = properties.getProperty("sms_platform_data");//sms平台数据接口
	String sms_platform_contact = properties.getProperty("sms_platform_contact");//sms平台联系人
	String map_type = properties.getProperty("map_type");//地图类型
	String sms_platform = properties.getProperty("sms_platform");//sms平台
	String please_enter_sms_platform_name = properties.getProperty("please_enter_sms_platform_name");//请输入短信平台名称
	String please_enter_sms_platform_data = properties.getProperty("please_enter_sms_platform_data");//请输入短信接口数据
	String gateway_type = properties.getProperty("gateway_type");//网关类型
	String sensor_type = properties.getProperty("sensor_type");//传感器类型
	String lamp_type = properties.getProperty("lamp_type");//路灯类型
	String image = properties.getProperty("image");//路灯类型
	String view_gateway_net = properties.getProperty("view_gateway_net");//网关配置参数
	String total_gateway_node = properties.getProperty("total_gateway_node");//节点个数
	String gateway_net_number = properties.getProperty("gateway_net_number");//网络号
	String gateway_channel_number = properties.getProperty("gateway_channel_number");//通道号
	String gateway_concentrator_addr = properties.getProperty("gateway_concentrator_addr");//集中器地址
	String gateway_id = properties.getProperty("gateway_id");//网关ID
	String gateway_net_ip = properties.getProperty("gateway_net_ip");//网络ip
	String gateway_net_port = properties.getProperty("gateway_net_port");//网络端口
	String please_select_page = properties.getProperty("please_select_page");//请选择你要查看的画面
	String client_node_info = properties.getProperty("client_node_info");//终端节点
	String current = properties.getProperty("current");//电流
	String lamp_state_page = properties.getProperty("lamp_state_page");//灯状态页面
	String sensor_state_page = properties.getProperty("sensor_state_page");//传感器状态页面
	String sensor_gatewayname = properties.getProperty("sensor_gatewayname");//传感器状态网关
	String max_voltage = properties.getProperty("max_voltage");//最大电压
	String max_current = properties.getProperty("max_current");//最大电流
	String set_voltage = properties.getProperty("set_voltage");//设置电压
	String set_current = properties.getProperty("set_current");//设置电流
	String name_en = properties.getProperty("name_en");//名称_英语
	String name_ch = properties.getProperty("name_ch");//名称_中文
	String gateway_type_comment = properties.getProperty("gateway_type_comment");//网关类型说明
	String manage_part_map= properties.getProperty("part_Map");//管理局部地图
	String coordidate= properties.getProperty("coordidate");//坐标
	String terminal_Num= properties.getProperty("terminal_Num");//终端数
	String picture= properties.getProperty("picture");//图片
	String add_part_map= properties.getProperty("add_part_map");//增加局部图片
	String confirm= properties.getProperty("confirm");//增加局部图片
	String part_map_markerInfo = properties.getProperty("part_map_markerInfo");//局部图片注点信息
	String part_map_name = properties.getProperty("part_map_name");//part map maker name
	String part_map_pic = properties.getProperty("part_map_pic");//part_map_pic
	String part_map_coordinate =properties.getProperty("part_map_coordinate");//part map maker name
	String part_map_add =properties.getProperty("part_map_add");//增加局部图片
	String please_choose_jpg =properties.getProperty("please_choose_jpg");//选择局部图片
	String part_map_delete_light =properties.getProperty("part_map_delete_light");//删除路灯配置
	String part_map_confirm_light =properties.getProperty("part_map_confirm_light");//确定路灯配置
	String part_map_load_light =properties.getProperty("part_map_load_light");//确定需要该位置加载路灯吗?
	String part_map_load_light_place=properties.getProperty("part_map_load_light_place");//确定需要该位置加载路灯吗?
	String part_map_light_exists=properties.getProperty("part_map_light_exists");//该路灯已经存在，不能重复添加，可以移动路灯位置
	String part_map_light_del_success=properties.getProperty("part_map_light_del_success");//该路灯已经删除成功
	String part_map_light_del_confirm=properties.getProperty("part_map_light_del_confirm");//请选择需要加载的路灯
	String part_map_light_deleted=properties.getProperty("part_map_light_deleted");//请选择需要加载的路灯
	String part_map_light_save_finished=properties.getProperty("part_map_light_save_finished");//请选择需要加载的路灯
	String part_map_noLight_need_save=properties.getProperty("part_map_noLight_need_save");//请选择需要加载的路灯
	String part_map_light_notexist_inPart =properties.getProperty("part_map_light_notexist_inPart");//请选择需要加载的路灯
	String Part_map_light_input_mapname=properties.getProperty("Part_map_light_input_mapname");//请输入局部图名称
	String Part_map_light_input_Coordinate=properties.getProperty("Part_map_light_input_Coordinate");//请输入局部地址坐标
	String Part_map_addLightToPartMapFailuer = properties.getProperty("Part_map_addLightToPartMapFailuer");//保存已经添加在局部地图上的路灯失败
	String Part_map_delLightFromPartMapFailed= properties.getProperty("Part_map_delLightFromPartMapFailed");//保存已经添加在局部地图上的路灯失败
	String make_sure_del_strategyset = properties.getProperty("make_sure_del_strategyset");//确定要删除所选的策略包吗？
	String strategy_set = properties.getProperty("strategy_set");//策略包
	String apply = properties.getProperty("apply");//应用
	String make_sure_apply_strategyset = properties.getProperty("make_sure_apply_strategyset");//确定要应用所选择的策略包吗？
	String add_apply_strategyset = properties.getProperty("add_apply_strategyset");//选择策略包
	String del_apply_strategyset = properties.getProperty("del_apply_strategyset");//删除策略包
	String change_gateway = properties.getProperty("change_gateway");//更换网关
	String report_error = properties.getProperty("report_error");//误报
	String submit = properties.getProperty("submit");//提交
	String misinformation = properties.getProperty("misinformation");//误报说明
	String please_input_ch_name = properties.getProperty("please_input_ch_name");//请输入中文名
	String please_input_en_name = properties.getProperty("please_input_en_name");//请输入英文名
	String please_input_max_vol = properties.getProperty("please_input_max_vol");//请输入最大电压
	String please_input_max_curr = properties.getProperty("please_input_max_curr");//请输入最大电流
	String please_input_set_vol = properties.getProperty("please_input_set_vol");//请输入设置电压
	String please_input_set_curr = properties.getProperty("please_input_set_curr");//请输入设置电流
	String strategyset_member = properties.getProperty("strategyset_member");//策略成员
	String group = properties.getProperty("group");//分组
	String forbitModifyPartMap = properties.getProperty("forbitModifyPartMap");//当前地图局部图不存在，不能修改。请选择另外分组或网关。
	String part_map_del_confirm =properties.getProperty("part_map_del_confirm");//确定要删除局部地图吗？
	String part_map_serchresult =properties.getProperty("part_map_serchresult");//确定要删除局部地图吗？
	String part_map_select = properties.getProperty("part_map_select");//确定要删除局部地图吗？
	String refresh_date = properties.getProperty("refresh_date");//刷新时间
	String node_address = properties.getProperty("node_address");//节点地址
	String node_name = properties.getProperty("node_name");//节点名称
	String node_number = properties.getProperty("node_number");//节点编号
	String node_type = properties.getProperty("node_type");//节点类型
	String lamp_config_page = properties.getProperty("lamp_config_page");//路灯配置页面
	String sensor_config_page = properties.getProperty("sensor_config_page");//传感器配置页面
	String sensor_config_gatewayname = properties.getProperty("sensor_config_gatewayname");//传感器配置列表 网关
	String lamp_config_gatewayname = properties.getProperty("lamp_config_gatewayname");//路灯配置列表 网关
	String pls_select_strategyset = properties.getProperty("pls_select_strategyset");//请选择需要删除的策略包
	String PartMap_Light_No_Exists  = properties.getProperty("PartMap_Light_No_Exists");//	路灯在地图上不存在，请检查路灯参数(亮度值等相关参数）
	String partmap_already_added  = properties.getProperty("partmap_already_added");// 已经加入其他局部图,不可重复加入！
	String light_name = properties.getProperty("light_name");//label:路灯名称
	String part_name =  properties.getProperty("part_name");//label:局部图名称
	String light_select =  properties.getProperty("light_select");//label:路灯选择
	String partMap_light_delconfirm =  properties.getProperty("partMap_light_delconfirm");//label:路灯确认删除确认
	String make_sure_delete_group =  properties.getProperty("make_sure_delete_group");//label:确定要删除分组?
	String apply_strategyset_failed =  properties.getProperty("apply_strategyset_failed");//label:应用策略包失败！
	String del_strategyset_failed =  properties.getProperty("del_strategyset_failed");//label:删除策略包失败！
	String available_gateway =  properties.getProperty("available_gateway");//label:可替换的网关
	String make_sure_change_gateway =  properties.getProperty("make_sure_change_gateway");//label:确定更换此网关	
	String revoke =  properties.getProperty("revoke");//label:撤销
	String achieve =  properties.getProperty("achieve");//label:完成
	String make_sure_cancel_change_gateway =  properties.getProperty("make_sure_cancel_change_gateway");//label:确定撤销更换此网关
	String fault_time = properties.getProperty("fault_time");//label:故障时间
	String fault_no = properties.getProperty("fault_no");//label:故障编号
	String please_enter_fault_no = properties.getProperty("please_enter_fault_no");//label:请输入故障编号
	String please_enter_node_no = properties.getProperty("please_enter_node_no");//label:请输入节点编号
	String please_enter_node_name = properties.getProperty("please_enter_node_name");//label:请输入节点名称
	String fault_device_type = properties.getProperty("fault_device_type");//label:故障设备类型
	String node = properties.getProperty("node");//label:节点
	String repair_operate = properties.getProperty("repair_operate");//label:修复操作
	String please_choose_maintainer = properties.getProperty("please_choose_maintainer");//label:请选择修复人
	String please_enter_repair_operate = properties.getProperty("please_enter_repair_operate");//label:请输入修复操作
	String fault_detail = properties.getProperty("fault_detail");//label:故障信息
	String node_detail = properties.getProperty("node_detail");//label:节点信息
	String please_enter_registrant = properties.getProperty("please_enter_registrant");//label:节点信息
	String please_enter_maintainer = properties.getProperty("please_enter_maintainer");//label:节点信息
	String please_select_device_type = properties.getProperty("please_select_device_type");//label:节点信息
	String sms_destination_setting = properties.getProperty("sms_destination_setting");//label:设定短信发送对象
	String remind_admin = properties.getProperty("remind_admin");//label:是否提醒自己
	String sms_destination = properties.getProperty("sms_destination");//label:短信发送对象
	String please_input_device_address = properties.getProperty("please_input_device_address");//label:请输入设备地址
	String please_input_sms_to_who = properties.getProperty("please_input_sms_to_who");//label:请选择短信发送对象
	String add_sms_setting = properties.getProperty("add_sms_setting");//label:请选择短信发送对象
	String add_duplicate = properties.getProperty("add_duplicate");//label:请选择短信发送对象
	String lamp_power_collection = properties.getProperty("lamp_power_collection");//label:灯能耗统计图
	String lamp_sumtime_collection = properties.getProperty("lamp_sumtime_collection");//label:灯时长统计图
	String download_node_info = properties.getProperty("download_node_info");//label:节点信息下载
	
%>